name: ItemArchiveReimagined
version: '${project.version}'
main: net.txsla.itemarchivereimagined.ItemArchiveReimagined
api-version: '1.20'

permissions :
  archive.public:
    description: "Allows the average player to interact with the archive"
    default-permission: true
    default: true
  archive.tester:
    description: "Allows the player to access debug features"
    default-permission: true
    default: true
  archive.editor:
    description: "Allows the player to edit archives that they have been added to"
    default-permission: true
    default: true

commands:
  submit-ban:
    description: "Bans a player from submitting items."
    usage: "/submit_ban <archive> <player>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  add-editor:
    description: "Adds an editor to the archive"
    usage: "/add-editor <archive> <player>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  count-items:
    description: "Counts the items in a vault"
    usage: "/count-items <vault>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  remove-item:
    description: "Removes an item(s) from an archive"
    usage: "/remove-item <archive> <args>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  edit:
    description: "Edit the properties of an archive"
    usage: "/edit <archive> <property> <args>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  submit:
    description: "Submit an item to the archives"
    usage: "/submit <archive>"
    aliases: [ ]
    permission: archive.public
    permission-message: "You do not have permission to use this command"
  submitRaw:
    description: "Submit an item to the archives"
    usage: "/submit <archive> <gui|hand|hotbar|inventory>"
    aliases: []
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  create-archive:
    description: "Create a new Archive"
    usage: "/create <archive>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  raw:
    description: "view a vault raw"
    usage: "/raw <vault>"
    aliases: []
    permission: archive.tester
    permission-message: "You do not have permission to use this command"
  loadoldarchive:
    description: "add items from an old archive file"
    usage: "/loadoldarchive <vault>"
    aliases: [ ]
    permission: archive.editor
    permission-message: "You do not have permission to use this command"
  search:
    description: "Search a vault"
    usage: "/search <vault> <parameter> <args>"
    aliases: [ ]
    permission: archive.public
    permission-message: "You do not have permission to use this command"
  open:
    description: "Open an archive"
    usage: "/open <archive> <int page>"
    aliases: [ ]
    permission: archive.public
    permission-message: "You do not have permission to use this command"
  openDemoInventory:
    description: "Opens a demo inventory"
    usage: "/openDemoInventory <vault> <int inventory> <bool>"
    aliases: [ ]
    permission: archive.tester
    permission-message: "You do not have permission to use this command"